export enum ActivityEnum {
    Registered = 'Registered',
    Updated_User_Info = 'Updated User Info',
    Logged_In = 'Logged In',
    Logged_Out = 'Logged Out',
    Created_a_Post = 'Created a Post',
    Edited_a_Post = 'Edited a Post',
    Deleted_a_Post = 'Deleted a Post',
    Liked_a_Post = 'Liked a Post',
    Unliked_a_Post = 'Unliked a Post',
    Commented_a_Post = 'Commented a Post',
    Deleted_a_Comment_of_a_Post = 'Deleted a Comment of a Post',
    Had_a_New_Following = 'Had a New Following',
    Unfollowed_a_Following = 'Unfollowed a Following',
    Had_a_New_Follower = 'Had a New Follower',
    A_follower_unfollowed = 'A follower unfollowed',
    Created_a_Story = 'Created a Story',
    Edited_a_Story = 'Edited a Story',
    Deleted_a_Story = 'Deleted a Story',
    Liked_a_Story = 'Liked a Story',
    Unlike_a_Story = 'Unlike a Story',
    Commented_a_Story = 'Commented a Story',
    Delete_a_Comment_of_a_Story = 'Delete a Comment of a Story',
}